[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pas-à-pas Nubo"
authors = [{name = "MMoussaoui", email = "mohamed.moussaoui@wavestone.com"}]
dynamic = ["version", "description"]
